### ISSUE TITLE
The SMD model checkpoint not found

### ISSUE THREAD

**Issue by LooperXX** [HLTCHKUST/ke-dialogue#2]
Thank you for your awesome work!
The GPT2+KE model checkpoint on the SMD data set is not available, could you please provide it correctly?

**Comment by yana-xuyan** [comment]
Hi, sorry for the late reply. The download link of the SMD model checkpoint is updated. Could you please try downloading it again?

**Comment by LooperXX** [comment]
Thank you for your reply and update! The SMD model checkpoint can be downloaded normally.
