### ISSUE TITLE
kb_types.json not found

### ISSUE THREAD

**Issue by LooperXX** [HLTCHKUST/ke-dialogue#3]
Thank you for your awesome work!
When I try to run the following command (from your code repository, link):
```shell
python generate_dialogues_SMD.py --split test --dialogue_path ./templates/weather_template.txt --domain weather --num_augmented_dialogue 100 --output_folder ./SMD/test
```
The `kb_types.json` does not exist but the #709 in generate_dialogues_SMD.py need it. I cannot find the generate process of this file in your release code.

**Comment by yana-xuyan** [comment]
Hi, sorry for the late reply. I already updated the processed data and included the missing file. You can find it under [path to the smd folder]/SMD/KBs. Please tell me if there's any problem with the code and thank you for your interest!

**Comment by LooperXX** [comment]
Thank you for your reply and update! The `kb_types.json` is now available for download.
