### ISSUE TITLE
The SMD dataset not found

### ISSUE THREAD

**Issue by ShaneTian** [HLTCHKUST/ke-dialogue#4]
The [URL of preprocessed SMD dataset](https://drive.google.com/open?id=1p5FgDcXYPp3s0MzQSbAi-ixqRxNhtfXX) is not available, could you please provide it correctly? @yana-xuyan

**Comment by yana-xuyan** [comment]
Hi, could you please try this link: [https://drive.google.com/open?id=1TU5IRFy-cQ9xlckJUdLmSJmY7qTaquP8](https://drive.google.com/open?id=1TU5IRFy-cQ9xlckJUdLmSJmY7qTaquP8)?
I also update the link in the README.md file.

**Comment by ShaneTian** [comment]
It is available. Thank you!
