### ISSUE TITLE
OpenDialKG dataset format

### ISSUE THREAD

**Issue by zhaone** [HLTCHKUST/ke-dialogue#5]
Hi, met some confusing issues when running your code on OpenDialKG dataset.

- At https://github.com/HLTCHKUST/ke-dialogue/blob/7f5a68022619d9275ece7d88ff951fae30c7de3d/modeling/opendialkg/utils/preprocessDIALKG.py#L69 you read `json` file as input but the dataset you provide is in format `csv` and some keys used in code are also not available in the dataset file. I wonder if you upload the right dataset file? or I missed some preprocessing procedure?

- At https://github.com/HLTCHKUST/ke-dialogue/blob/7f5a68022619d9275ece7d88ff951fae30c7de3d/knowledge_embed/opendialkg/generate_dialogues_DIALKG.py#L115, are you sure it is `count_fulfilled <= stop_count` rather ran `count_fulfilled >= stop_count`. Your current code stops always at iteration 1.

- It's good that you provide a `result.json` in the checkpoint folder but no corresponding dialogue history is provided ... It's really hard to reproduce your experiment.

Can you provide the dataset file that can be used for evaluation or complete the `result.json` by adding dialogue history or `dialogue_id`.

**Comment by SamuelCahyawijaya** [comment]
Hi @zhaone,

Thank you for noticing! We have some problems with the published code for OpenDialKG as we lost the latest experiment code for this dataset before. We will fix the issues on the script and the missing `json` files as soon as possible.

For the `result.json`, please find the `test.json.zip` attached here. You can unzip the file to get the original test file that we use. To get the complete dialogue with all the history, you can replace all `SYS` utterances on the `test.json` with the 
utterances on the `result.json` in an ordered manner.

[test.json.zip](https://github.com/HLTCHKUST/ke-dialogue/files/8042395/test.json.zip)

Please let me know if you have any further questions!
